name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/haproxy:${{ secrets.DOCKER_TAG }}
    - name: Save Docker image to file
      run: |
        docker save ${{ secrets.DOCKER_USERNAME }}/haproxy:${{ secrets.DOCKER_TAG }} | gzip > haproxy_${{ secrets.DOCKER_TAG }}.tar.gz

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: haproxy
        path: haproxy_${{ secrets.DOCKER_TAG }}.tar.gz    
